//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantoã_Arquitetura.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_account
    {
        public int id_account { get; set; }
        public string nm_account { get; set; }
        public string nr_identification { get; set; }
        public string ds_note { get; set; }
        public decimal vl_value { get; set; }
        public Nullable<bool> bt_account { get; set; }
    }
}
