//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantoã_Arquitetura.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bankaccount
    {
        public int id_bankAccount { get; set; }
        public string nm_bank { get; set; }
        public string nr_account { get; set; }
        public int nr_agency { get; set; }
        public string ds_typePerson { get; set; }
    }
}
