//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantoã_Arquitetura.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cnae
    {
        public int id_enterprise { get; set; }
        public string dt_tableYear { get; set; }
        public string ds_activity { get; set; }
        public string nr_cnae { get; set; }
    
        public virtual tb_enterprise tb_enterprise { get; set; }
    }
}
