//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantoã_Arquitetura.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_crm
    {
        public int id_client { get; set; }
        public string ds_mood { get; set; }
        public string ds_note { get; set; }
    
        public virtual tb_client tb_client { get; set; }
    }
}
