//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantoã_Arquitetura.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_client()
        {
            this.tb_iten = new HashSet<tb_iten>();
            this.tb_sale = new HashSet<tb_sale>();
        }
    
        public int id_client { get; set; }
        public string nm_firstName { get; set; }
        public string nm_lastName { get; set; }
        public string nr_rg { get; set; }
        public string nr_cpf { get; set; }
        public string ds_sex { get; set; }
        public string dt_birth { get; set; }
        public string ds_state { get; set; }
        public string nr_cep { get; set; }
        public string ds_address { get; set; }
        public string ds_note { get; set; }
        public string nr_cellphone { get; set; }
        public string nr_tellphone { get; set; }
        public string ds_email { get; set; }
    
        public virtual tb_crm tb_crm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_iten> tb_iten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_sale> tb_sale { get; set; }
    }
}
