//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantoã_Arquitetura.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_department
    {
        public int id_department { get; set; }
        public int id_emp { get; set; }
        public string nm_department { get; set; }
    
        public virtual tb_employees tb_employees { get; set; }
    }
}
