//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantoã_Arquitetura.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_iten
    {
        public int id_iten { get; set; }
        public int id_sale { get; set; }
        public int id_client { get; set; }
        public int id_product { get; set; }
        public int vl_qtdProduct { get; set; }
    
        public virtual tb_client tb_client { get; set; }
        public virtual tb_sale tb_sale { get; set; }
        public virtual tb_product tb_product { get; set; }
    }
}
