//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantoã_Arquitetura.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_points
    {
        public int id_point { get; set; }
        public int id_emp { get; set; }
        public string hr_input { get; set; }
        public string hr_output { get; set; }
        public string hr_intInput { get; set; }
        public string hr_intOutput { get; set; }
        public string hr_toPay { get; set; }
        public string dt_points { get; set; }
    
        public virtual tb_employees tb_employees { get; set; }
    }
}
