//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantoã_Arquitetura.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_provider
    {
        public int id_provider { get; set; }
        public string nm_provider { get; set; }
        public string nm_name { get; set; }
        public string ds_typePerson { get; set; }
        public string nr_identification { get; set; }
        public string ds_email { get; set; }
        public string ds_state { get; set; }
        public string nr_cep { get; set; }
        public string ds_address { get; set; }
        public string ds_note { get; set; }
        public string nr_cellphone { get; set; }
        public string nr_tellphone { get; set; }
    }
}
